"""modify property_id to parcel_master

Revision ID: 33a05c2097a5
Revises: c75d01ff6716
Create Date: 2026-07-15 17:24:34.650394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a05c2097a5'
down_revision: Union[str, Sequence[str], None] = 'c75d01ff6716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'parcel_master', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parcel_master', schema='propertytax', type_='foreignkey')
    # ### end Alembic commands ###
