"""Property_location & ward No 

Revision ID: 443f7f93194e
Revises: b0b526570b09
Create Date: 2026-07-20 11:12:29.147783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443f7f93194e'
down_revision: Union[str, Sequence[str], None] = 'b0b526570b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the column as nullable first
    op.add_column(
        'property_details',
        sa.Column(
            'property_location',
            sa.String(length=100),
            nullable=True
        ),
        schema='propertytax'
    )

    # Populate existing rows
    op.execute("""
        UPDATE propertytax.property_details
        SET property_location = 'Unknown'
        WHERE property_location IS NULL;
    """)

    # Make the column NOT NULL
    op.alter_column(
        'property_details',
        'property_location',
        existing_type=sa.String(length=100),
        nullable=False,
        schema='propertytax'
    )

    # Change ward_no from Integer to String
    op.alter_column(
        'survey_information',
        'ward_no',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=20),
        existing_nullable=False,
        schema='propertytax'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_information', 'ward_no',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='propertytax')
    op.drop_column('property_details', 'property_location', schema='propertytax')
    # ### end Alembic commands ###
