"""modify fk , create property id fk

Revision ID: 4cc3b14d36f2
Revises: 2239f87530fc
Create Date: 2026-07-16 10:14:39.210073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc3b14d36f2'
down_revision: Union[str, Sequence[str], None] = '2239f87530fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_collected_parcel_no_fkey'), 'documents_collected', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('gis_information_parcel_no_fkey'), 'gis_information', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('land_building_information_parcel_no_fkey'), 'land_building_information', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('occupier_details_parcel_no_fkey'), 'occupier_details', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('owner_declaration_parcel_no_fkey'), 'owner_declaration', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('owner_details_parcel_no_fkey'), 'owner_details', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('property_details_parcel_no_fkey'), 'property_details', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('smart_addressing_parcel_no_fkey'), 'smart_addressing', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('survey_information_parcel_no_fkey'), 'survey_information', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('surveyor_remarks_parcel_no_fkey'), 'surveyor_remarks', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('tax_related_information_parcel_no_fkey'), 'tax_related_information', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('usage_details_parcel_no_fkey'), 'usage_details', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('utility_connections_parcel_no_fkey'), 'utility_connections', schema='propertytax', type_='foreignkey')
    op.drop_constraint(op.f('verification_parcel_no_fkey'), 'verification', schema='propertytax', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('verification_parcel_no_fkey'), 'verification', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('utility_connections_parcel_no_fkey'), 'utility_connections', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('usage_details_parcel_no_fkey'), 'usage_details', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('tax_related_information_parcel_no_fkey'), 'tax_related_information', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('surveyor_remarks_parcel_no_fkey'), 'surveyor_remarks', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('survey_information_parcel_no_fkey'), 'survey_information', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('smart_addressing_parcel_no_fkey'), 'smart_addressing', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('property_details_parcel_no_fkey'), 'property_details', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('owner_details_parcel_no_fkey'), 'owner_details', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('owner_declaration_parcel_no_fkey'), 'owner_declaration', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('occupier_details_parcel_no_fkey'), 'occupier_details', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('land_building_information_parcel_no_fkey'), 'land_building_information', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('gis_information_parcel_no_fkey'), 'gis_information', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    op.create_foreign_key(op.f('documents_collected_parcel_no_fkey'), 'documents_collected', 'parcel_master', ['parcel_no'], ['parcel_no'], source_schema='propertytax', referent_schema='propertytax')
    # ### end Alembic commands ###
