"""modify 3rd property_id to parcel_master

Revision ID: 55f09ff1f037
Revises: 67d99b3ae389
Create Date: 2026-07-15 17:31:34.868229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f09ff1f037'
down_revision: Union[str, Sequence[str], None] = '67d99b3ae389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
