"""Initial migration

Revision ID: 5d783b607860
Revises: 
Create Date: 2026-07-15 14:32:16.770043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d783b607860'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_master',
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('parcel_no'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_parcel_master_parcel_no'), 'parcel_master', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('documents_collected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('aadhaar_copy', sa.String(length=500), nullable=True),
    sa.Column('electricity_bill', sa.String(length=500), nullable=True),
    sa.Column('water_bill', sa.String(length=500), nullable=True),
    sa.Column('sale_deed', sa.String(length=500), nullable=True),
    sa.Column('property_tax_receipt', sa.String(length=500), nullable=True),
    sa.Column('building_permission', sa.String(length=500), nullable=True),
    sa.Column('other_documents', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_documents_collected_parcel_no'), 'documents_collected', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('gis_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('gis_property_polygon_available', sa.Boolean(), nullable=False),
    sa.Column('property_boundary_verified', sa.Boolean(), nullable=False),
    sa.Column('geo_tag_completed', sa.Boolean(), nullable=False),
    sa.Column('property_photo_captured', sa.Boolean(), nullable=False),
    sa.Column('front_elevation_photo', sa.Boolean(), nullable=False),
    sa.Column('name_plate_photo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_gis_information_parcel_no'), 'gis_information', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('land_building_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('plot_area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ground_floor_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('first_floor_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('second_floor_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('third_floor_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_builtup_area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('number_of_floors', sa.Integer(), nullable=False),
    sa.Column('year_of_construction', sa.Integer(), nullable=True),
    sa.Column('building_age', sa.Integer(), nullable=True),
    sa.Column('construction_type', sa.String(length=20), nullable=False),
    sa.Column('roof_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_land_building_information_parcel_no'), 'land_building_information', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('occupier_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('occupier_name', sa.String(length=200), nullable=True),
    sa.Column('mobile_number', sa.String(length=10), nullable=True),
    sa.Column('occupancy_status', sa.String(length=20), nullable=False),
    sa.Column('tenant_since', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_occupier_details_parcel_no'), 'occupier_details', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('owner_declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('owner_declaration_accepted', sa.Boolean(), nullable=False),
    sa.Column('owner_signature', sa.String(length=500), nullable=True),
    sa.Column('owner_refusal_reason', sa.String(length=500), nullable=True),
    sa.Column('surveyor_signature', sa.String(length=500), nullable=False),
    sa.Column('declaration_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_owner_declaration_parcel_no'), 'owner_declaration', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('owner_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('father_husband_name', sa.String(length=200), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_no', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('correspondence_address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_owner_details_parcel_no'), 'owner_details', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('property_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('property_type', sa.String(length=30), nullable=False),
    sa.Column('property_status', sa.String(length=30), nullable=False),
    sa.Column('building_permission_available', sa.Boolean(), nullable=False),
    sa.Column('property_ownership', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_property_details_parcel_no'), 'property_details', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('smart_addressing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('ddn_generated', sa.Boolean(), nullable=False),
    sa.Column('ddn_sticker_affixed', sa.Boolean(), nullable=False),
    sa.Column('qr_code_affixed', sa.Boolean(), nullable=False),
    sa.Column('street_code', sa.String(), nullable=False),
    sa.Column('building_sequence_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('street_code', 'building_sequence_no', name='uq_street_building_sequence'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_smart_addressing_parcel_no'), 'smart_addressing', ['parcel_no'], unique=False, schema='propertytax')
    op.create_index(op.f('ix_propertytax_smart_addressing_street_code'), 'smart_addressing', ['street_code'], unique=False, schema='propertytax')
    op.create_table('survey_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('survey_id', sa.String(length=50), nullable=False),
    sa.Column('survey_date', sa.DateTime(), nullable=False),
    sa.Column('surveyor_name', sa.String(length=150), nullable=False),
    sa.Column('surveyor_id', sa.String(length=30), nullable=False),
    sa.Column('ward_no', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('colony_locality', sa.String(length=150), nullable=False),
    sa.Column('street_road_name', sa.String(length=150), nullable=False),
    sa.Column('lane_no', sa.String(length=20), nullable=True),
    sa.Column('existing_property_id', sa.String(length=50), nullable=True),
    sa.Column('digital_door_number', sa.String(length=50), nullable=True),
    sa.Column('gps_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('gps_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_survey_information_id'), 'survey_information', ['id'], unique=False, schema='propertytax')
    op.create_index(op.f('ix_propertytax_survey_information_parcel_no'), 'survey_information', ['parcel_no'], unique=False, schema='propertytax')
    op.create_index(op.f('ix_propertytax_survey_information_survey_id'), 'survey_information', ['survey_id'], unique=True, schema='propertytax')
    op.create_table('surveyor_remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('surveyor_remarks', sa.String(length=1000), nullable=True),
    sa.Column('supervisor_remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_surveyor_remarks_parcel_no'), 'surveyor_remarks', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('tax_related_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('existing_property_tax_no', sa.String(length=50), nullable=True),
    sa.Column('tax_paid_till', sa.Date(), nullable=True),
    sa.Column('outstanding_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exempted_property', sa.Boolean(), nullable=False),
    sa.Column('exemption_category', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('existing_property_tax_no'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_tax_related_information_parcel_no'), 'tax_related_information', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('usage_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('primary_use', sa.String(length=30), nullable=False),
    sa.Column('mixed_use', sa.Boolean(), nullable=False),
    sa.Column('commercial_activity', sa.String(length=50), nullable=True),
    sa.Column('occupancy', sa.String(length=20), nullable=False),
    sa.Column('number_of_families', sa.Integer(), nullable=False),
    sa.Column('number_of_shops', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_usage_details_parcel_no'), 'usage_details', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('utility_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('water_connection_no', sa.String(length=30), nullable=True),
    sa.Column('sewer_connection', sa.Boolean(), nullable=False),
    sa.Column('electricity_consumer_no', sa.String(length=30), nullable=True),
    sa.Column('gas_connection', sa.Boolean(), nullable=False),
    sa.Column('trade_license_no', sa.String(length=30), nullable=True),
    sa.Column('factory_license_no', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('water_connection_no'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_utility_connections_parcel_no'), 'utility_connections', ['parcel_no'], unique=False, schema='propertytax')
    op.create_table('verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('unassessed_property', sa.Boolean(), nullable=False),
    sa.Column('under_assessed_property', sa.Boolean(), nullable=False),
    sa.Column('property_use_changed', sa.Boolean(), nullable=False),
    sa.Column('additional_floor_constructed', sa.Boolean(), nullable=False),
    sa.Column('boundary_changed', sa.Boolean(), nullable=False),
    sa.Column('ownership_changed', sa.Boolean(), nullable=False),
    sa.Column('demolished_property', sa.Boolean(), nullable=False),
    sa.Column('new_property', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_no'], ['propertytax.parcel_master.parcel_no'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_verification_parcel_no'), 'verification', ['parcel_no'], unique=False, schema='propertytax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propertytax_verification_parcel_no'), table_name='verification', schema='propertytax')
    op.drop_table('verification', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_utility_connections_parcel_no'), table_name='utility_connections', schema='propertytax')
    op.drop_table('utility_connections', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_usage_details_parcel_no'), table_name='usage_details', schema='propertytax')
    op.drop_table('usage_details', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_tax_related_information_parcel_no'), table_name='tax_related_information', schema='propertytax')
    op.drop_table('tax_related_information', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_surveyor_remarks_parcel_no'), table_name='surveyor_remarks', schema='propertytax')
    op.drop_table('surveyor_remarks', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_survey_information_survey_id'), table_name='survey_information', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_survey_information_parcel_no'), table_name='survey_information', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_survey_information_id'), table_name='survey_information', schema='propertytax')
    op.drop_table('survey_information', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_smart_addressing_street_code'), table_name='smart_addressing', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_smart_addressing_parcel_no'), table_name='smart_addressing', schema='propertytax')
    op.drop_table('smart_addressing', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_property_details_parcel_no'), table_name='property_details', schema='propertytax')
    op.drop_table('property_details', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_owner_details_parcel_no'), table_name='owner_details', schema='propertytax')
    op.drop_table('owner_details', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_owner_declaration_parcel_no'), table_name='owner_declaration', schema='propertytax')
    op.drop_table('owner_declaration', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_occupier_details_parcel_no'), table_name='occupier_details', schema='propertytax')
    op.drop_table('occupier_details', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_land_building_information_parcel_no'), table_name='land_building_information', schema='propertytax')
    op.drop_table('land_building_information', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_gis_information_parcel_no'), table_name='gis_information', schema='propertytax')
    op.drop_table('gis_information', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_documents_collected_parcel_no'), table_name='documents_collected', schema='propertytax')
    op.drop_table('documents_collected', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_parcel_master_parcel_no'), table_name='parcel_master', schema='propertytax')
    op.drop_table('parcel_master', schema='propertytax')
    # ### end Alembic commands ###
