"""modify 2nd property_id to parcel_master

Revision ID: 67d99b3ae389
Revises: 33a05c2097a5
Create Date: 2026-07-15 17:27:01.536661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d99b3ae389'
down_revision: Union[str, Sequence[str], None] = '33a05c2097a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('parcel_master_property_id_fkey'), 'parcel_master', schema='propertytax', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('parcel_master_property_id_fkey'), 'parcel_master', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    # ### end Alembic commands ###
