"""modify user_auth table

Revision ID: b0b526570b09
Revises: b47920017fdd
Create Date: 2026-07-16 16:47:40.618116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b526570b09'
down_revision: Union[str, Sequence[str], None] = 'b47920017fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('surveyor_name', sa.String(length=200), nullable=False),
    sa.Column('surveyor_id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surveyor_id'),
    sa.UniqueConstraint('username'),
    schema='propertytax'
    )
    op.create_index(op.f('ix_propertytax_user_auth_id'), 'user_auth', ['id'], unique=False, schema='propertytax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propertytax_user_auth_id'), table_name='user_auth', schema='propertytax')
    op.drop_table('user_auth', schema='propertytax')
    # ### end Alembic commands ###
