"""Add property_id to parcel_master

Revision ID: c6b556dba5c6
Revises: 5d783b607860
Create Date: 2026-07-15 15:33:28.730674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b556dba5c6'
down_revision: Union[str, Sequence[str], None] = '5d783b607860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel_master', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_parcel_master_property_id'), 'parcel_master', ['property_id'], unique=True, schema='propertytax')
    op.add_column('verification', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_verification_property_id'), 'verification', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'verification', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_verification_property_id'), table_name='verification', schema='propertytax')
    op.drop_column('verification', 'property_id', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_parcel_master_property_id'), table_name='parcel_master', schema='propertytax')
    op.drop_column('parcel_master', 'property_id', schema='propertytax')
    # ### end Alembic commands ###
