"""Into another tables property_id to parcel_master

Revision ID: c75d01ff6716
Revises: c6b556dba5c6
Create Date: 2026-07-15 15:35:23.947341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75d01ff6716'
down_revision: Union[str, Sequence[str], None] = 'c6b556dba5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_collected', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_documents_collected_property_id'), 'documents_collected', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'documents_collected', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('gis_information', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_gis_information_property_id'), 'gis_information', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'gis_information', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('land_building_information', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_land_building_information_property_id'), 'land_building_information', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'land_building_information', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('occupier_details', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_occupier_details_property_id'), 'occupier_details', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'occupier_details', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('owner_declaration', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_owner_declaration_property_id'), 'owner_declaration', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'owner_declaration', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('owner_details', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_owner_details_property_id'), 'owner_details', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'owner_details', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('property_details', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_property_details_property_id'), 'property_details', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'property_details', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('smart_addressing', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_smart_addressing_property_id'), 'smart_addressing', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'smart_addressing', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('survey_information', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_survey_information_property_id'), 'survey_information', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'survey_information', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.drop_column('survey_information', 'existing_property_id', schema='propertytax')
    op.add_column('surveyor_remarks', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_surveyor_remarks_property_id'), 'surveyor_remarks', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'surveyor_remarks', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('tax_related_information', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_tax_related_information_property_id'), 'tax_related_information', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'tax_related_information', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('usage_details', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_usage_details_property_id'), 'usage_details', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'usage_details', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    op.add_column('utility_connections', sa.Column('property_id', sa.String(length=50), nullable=False), schema='propertytax')
    op.create_index(op.f('ix_propertytax_utility_connections_property_id'), 'utility_connections', ['property_id'], unique=False, schema='propertytax')
    op.create_foreign_key(None, 'utility_connections', 'parcel_master', ['property_id'], ['property_id'], source_schema='propertytax', referent_schema='propertytax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utility_connections', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_utility_connections_property_id'), table_name='utility_connections', schema='propertytax')
    op.drop_column('utility_connections', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'usage_details', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_usage_details_property_id'), table_name='usage_details', schema='propertytax')
    op.drop_column('usage_details', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'tax_related_information', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_tax_related_information_property_id'), table_name='tax_related_information', schema='propertytax')
    op.drop_column('tax_related_information', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'surveyor_remarks', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_surveyor_remarks_property_id'), table_name='surveyor_remarks', schema='propertytax')
    op.drop_column('surveyor_remarks', 'property_id', schema='propertytax')
    op.add_column('survey_information', sa.Column('existing_property_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='propertytax')
    op.drop_constraint(None, 'survey_information', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_survey_information_property_id'), table_name='survey_information', schema='propertytax')
    op.drop_column('survey_information', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'smart_addressing', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_smart_addressing_property_id'), table_name='smart_addressing', schema='propertytax')
    op.drop_column('smart_addressing', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'property_details', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_property_details_property_id'), table_name='property_details', schema='propertytax')
    op.drop_column('property_details', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'owner_details', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_owner_details_property_id'), table_name='owner_details', schema='propertytax')
    op.drop_column('owner_details', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'owner_declaration', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_owner_declaration_property_id'), table_name='owner_declaration', schema='propertytax')
    op.drop_column('owner_declaration', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'occupier_details', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_occupier_details_property_id'), table_name='occupier_details', schema='propertytax')
    op.drop_column('occupier_details', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'land_building_information', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_land_building_information_property_id'), table_name='land_building_information', schema='propertytax')
    op.drop_column('land_building_information', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'gis_information', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_gis_information_property_id'), table_name='gis_information', schema='propertytax')
    op.drop_column('gis_information', 'property_id', schema='propertytax')
    op.drop_constraint(None, 'documents_collected', schema='propertytax', type_='foreignkey')
    op.drop_index(op.f('ix_propertytax_documents_collected_property_id'), table_name='documents_collected', schema='propertytax')
    op.drop_column('documents_collected', 'property_id', schema='propertytax')
    # ### end Alembic commands ###
