"""Update existing_property_id, tax rate zone 

Revision ID: cf3db6b7e845
Revises: 443f7f93194e
Create Date: 2026-07-20 15:50:02.564548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3db6b7e845'
down_revision: Union[str, Sequence[str], None] = '443f7f93194e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('smart_addressing', 'ddn_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='propertytax')
    op.alter_column('smart_addressing', 'ddn_sticker_affixed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='propertytax')
    op.alter_column('smart_addressing', 'qr_code_affixed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='propertytax')
    op.alter_column('smart_addressing', 'street_code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='propertytax')
    op.alter_column('smart_addressing', 'building_sequence_no',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='propertytax')
    op.add_column('survey_information', sa.Column('existing_property_id', sa.String(length=50), nullable=True), schema='propertytax')
    op.create_index(op.f('ix_propertytax_survey_information_existing_property_id'), 'survey_information', ['existing_property_id'], unique=False, schema='propertytax')
    op.add_column('tax_related_information', sa.Column('tax_rate_zone', sa.String(length=30), nullable=True), schema='propertytax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_related_information', 'tax_rate_zone', schema='propertytax')
    op.drop_index(op.f('ix_propertytax_survey_information_existing_property_id'), table_name='survey_information', schema='propertytax')
    op.drop_column('survey_information', 'existing_property_id', schema='propertytax')
    op.alter_column('smart_addressing', 'building_sequence_no',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='propertytax')
    op.alter_column('smart_addressing', 'street_code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='propertytax')
    op.alter_column('smart_addressing', 'qr_code_affixed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='propertytax')
    op.alter_column('smart_addressing', 'ddn_sticker_affixed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='propertytax')
    op.alter_column('smart_addressing', 'ddn_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='propertytax')
    # ### end Alembic commands ###
