from .parcel_master import ParcelMaster
from .survey_information import SurveyInformation
from .owner_details import OwnerDetails
from .occupier_details import OccupierDetails
from .property_details import PropertyDetails
from .land_building_information import LandBuildingInformation
from .usage_details import UsageDetails
from .tax_related_information import TaxRelatedInformation
from .utility_connections import UtilityConnections
from .gis_information import GISInformation
from .smart_addressing import SmartAddressing
from .verification import Verification
from .documents_collected import DocumentsCollected
from .surveyor_remarks import SurveyorRemarks
from .owner_declaration import OwnerDeclaration
from .user_auth import UserAuth